### PR TITLE
Baseimage testpr and bookworm

### PR DESCRIPTION
**Pull request by fredclausen**
## ADSB

- [x] radarbox build
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] readsb-proto
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] beast-splitter
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] fr24
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] radarvirtuel
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] tar1090
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] tar1090 telegraph
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] dump978
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] piaware
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] adsbx
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] adsbhub
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] opensky
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] planefinder
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] ultrafeeder
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] airspy
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
  

## ACARS

- [x] acarsdec
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] vdlm2dec
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] dumpvdl2
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] acars router
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] acars oxide
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] acarshub
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
  
## Other

- [x] rtlsdrairband
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good
- [x] Reverse Web Proxy
  - [x] Build against bookworm 
  - [x] Initial Test
  - [x] healthcheck
  - [x] Verified Good 
- [ ] Plane Fence
  - [ ] Build against bookworm 
  - [ ] Initial Test
  - [x] healthcheck
  - [ ] Verified Good

### CODE REVIEW

**Comment by fredclausen** [comment]
@kx1t @mikenye I'm plugging away at this. I've created a checklist above showing the status of everything. Am I missing any containers?

**Comment by fredclausen** [comment]
I'll also add that the checklist format is basically indicating if the thing builds under bookworm, have I run it (initial test) and the verified good will be once enough people run in and we know it works.

**Comment by dirkhh** [comment]
ummm - why is there no airspy container on your list?

**Comment by fredclausen** [comment]
> ummm - why is there no airspy container on your list?

Great question. It doesn't appear to be part of our CI (it should be) and this list was generated from the CI + my memory. Lemme add it

**Comment by fredclausen** [comment]
Alright, I think this is ready to go. Plane Fence will need kx1t's touch but I've got a PR ready for it that should enable a seamless transition. I'd say we give it more time for everyone to run it, but honestly, I don't think it's going to give us many headaches going forward.

Changes to common action:

* I may have messed this up, but previously there was a depedency on certain build paths for no_healthcheck and other builds to complete. I didn't see a reason for this, so all build paths (arch specific, no healthcheck, build manifest) should be parallel now
* `build_baseimage_test`. Boolean to indicate that this is being called to test against baseimage test images. Will use the sed statement in `build_baseimage_url` to update docker file. While not explicitly required, `no_healthcheck/version specific/arch specific` in all SDR-E callers of this action disable those build paths.
* `build_baseimage_url` is a sed statement (less the leading `s` and trailing `g`) used to change the FROM image URL to point to the baseimage test images. If `build_baseimage_test` is `false` then this value is ignored.
* `dockerfile_changes` was added to allow ultra and tar1090 to build using the common action. It is a sed statement, that if set, will update the dockerfile
* `docker_latest_tag` was added to allow ultra and tar1090 to build the telegraf images and not overwrite the `latest` tag of the non-telegraf version. Default is `latest`. Basically, if `build_latest` is set, the tag used when building the list of tags will include `docker_latest_tag`. If this is NOT set to `latest`, as of right now (and this should be fixed, I just now thought of it) any arch/version specific tags will get overwritten. Basically, if you want to set `docker_latest_tag` to a something not `latest` then disable arch/version builds for it. `ultra/tar1090:telegraf` are done this way.

General Changes:

* All of the SDR-E builds now use the common action for deploy except for ACARS Hub. My build process is so....unique, I don't want to mess with it quite yet. However, it functionally is the same as the common action.
* I did not touch any PR actions, although I probably should. Likely, it will be largely a copy / paste exercise from deploy to the pr action and disable pushes.
* Added in an input to the deploy action in the baseimage repo to build the main images, but NOT trigger any upstream rebuilds.
* Added in `DEPLOY_STATUS.MD` which is a simple MD file that shows the build status of all of the SDR-E deploy actions in one place
* Some of the SDR-E containers have changes in them which means that they will NOT build again under non-bookworm debians, and to make my life easier these changes have been all merged into their respective main/master branches. If, for some reason we need to roll back, it will be a manual process of updating container dockerfiles. The actual build action stuff shouldn't be needing any changes.
* All containers have switched to using wiede's MLAT client. muta's version was not bookworm safe. I see no reason to change this for the foreseeable future, but it's something to keep in mind.
* `/run/s6/services` is now `/run/s6/legacy-services`

Warnings:

* I honestly expect this to fail once we merge to main. The ONLY build path actually tested has been the baseimage-pr path. No arch, version specific, or healthcheck
* There may be an issue with MLAT. If so, this will require fixing from upstream.
* Because of the legacy-services thing, no container will now build against any non-v3 S6.
* Any future docker images, until we change the service files to non-legacy, will have to reference `/run/s6/legacy-services` instead of `/run/s6/services`
* Any future docker images should use the correct cont-env shebang (#!/command/with-contenv)
* Any future docker images should mark any files in `/etc/{cont.init, cont.finish, services.d, whatever S6 path I forgot}` as +x. Failure to do so will cause a startup error related to permissions on the `run` file

Things to do:

* Because of the warning above, I would like to merge this to main, stop the build, and retrigger the build but disable any upstream rebuild triggers. Once the rebuild of the base images is done we can go through and individually trigger the builds off to make sure they're doing what we want. Once we know that's all good, in the future we can just let it trigger on its own.
* We will need to migrate all of our S6 run files AND healthcheck framework to the new format. What that is, and what that will entail I don't know but I expect it to be a large pain.
* Related to the above, we will need to change all of the cont-env shebang lines. I didn't do this because it wasn't necessary to get S6 v3 working and I wanted to keep the breaking changes to a minimum.
* When we do the above, we will need to change the S6 v3 deploy script to remove `s6-overlay-symlinks-noarch` stuff. I think.
* Also, when we do the above there is a small hack I did in the S6 v3 overlay script to fix a shebang issue with `execlineb` and other things that apparently is a bug in their own symlinks. We could likely remove this once we've fixed the shebangs.
* It is likely I've cocked up some dockerhub name, no healthcheck/arch specific/version specific thing, either enabling/disabling as appropriate, or using the wrong method for versioning, etc. We will need to check those things to make sure I got it right. I tried my hardest, but there was an awful lot of stuff I was keeping in my head so I'm sure I got it wrong somewhere.
* I feel like we could potentially migrate rltsdrairband to the soapy image, and I may take the time to make a base image specifically for it. There seems to be little reason to build all of that nonsense over and over again in the airband container when in reality a decent chunk of it may be useful in a base image and shared.
* Healthchecks should be audited and see if we're hitting the mark with them. I feel like this issue mostly impacts new images and not the ones Mike created "back in the day", but if we've added features to these containers (tar1090 maybe?) then we should ensure HC is doing a thing with that. I can state with ceritude I'm missing the mark with HC on the ACARS stack.

This has been a marathon effort but it's as good as I can get it. Sorry for the massive novel.

**Review by mikenye — APPROVED** [review]
Amazing work. Truly a mammoth effort. We can always fix forward if something breaks.

**Pull request merged**
