### PR TITLE
Add in libseccomp2 checker for startup

### PR DESCRIPTION
**Pull request by fredclausen**
Using the `Buster-Docker-Fixes` `cont-init` script this change will do the following:

* Add the script to the `:base` tag image
* The script will check if `sleep` works properly. On a system with an old version of `libseccomp2` and `bullseye` images `sleep` appears to be an easy check to see if it fails. If it fails, the container won't start and will spam a message in to the logs indicating the user needs to fix their system.

ETA: Why did the build checks not build? `Dockerfile` was updated so every single stage should have kicked off a build....hmmm.

### CODE REVIEW

**Comment by fredclausen** [comment]
I think I fixed the CI issue. Renamed `Dockerfile` to `Dockerfile.base` and I think that corrects the issue with the file checker correctly picking up changes to it.

**Comment by fredclausen** [comment]
For some reason the CI doesn't run at all now on this branch. I've got no idea why.

(Edit as I'm typing....it literally kicked a build off as I'm typing this)

Latest commits now enable the following (or rather, should....) for on_pr:

* Any container that is re-built now pushes a package out under `<tagname>-test`
* Any child container checks for any of the parent(s) being rebuilt, and if so, patches the `FROM` line in the docker file for that container to use the `-test` tag for the parent

I feel this is advantageous for the following reasons:

* Before committing a PR we now have the option to build test containers of any dependent projects
* Any changes in the parent(s) of a child container will now be reflected in the build, which allows the CI to ensure the build works with the change(s) from the parent(s)

**Review by mikenye — APPROVED** [review]

**Comment by mikenye** [comment]
The idea to upload the test image and patch dockerfiles is clever. 

However, a better option may be to use GitHub artefacts. 

For the on_pr action, we could export the images build at all stages as artefacts. 

For any stage building on another image, they could simply download the artefact and install the image.

Images can be tagged as they should be in production. 

This way we're not pushing/pulling or having to patch anything.

See: https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow

I'm thinking `docker save`/`docker load` could be used.

Let me know what you think.

**Comment by fredclausen** [comment]
That’s a much better approach than what I came up with. I like it.

**Comment by mikenye** [comment]
Do you want to update your PR? Or would you like me to have a go on your branch?

**Comment by fredclausen** [comment]
You can have a go if you've got time. If not I'll look at it when I wake up tomorrow

**Comment by mikenye** [comment]
Just had a thought... not sure docker save/load will work correctly with multi-arch images. Will have to do some research. Maybe merge yours and we can revisit.

**Comment by mikenye** [comment]
Hi Fred, did some reading. It looks like until they implement an ability to import multi architecture images into buildx, we'll have to continue this method. 

Or, instead of doing a multi-arch image, we use a matrix to test each arch individually (which might be a good idea). 

Ref: https://github.com/docker/buildx/issues/847

**Comment by fredclausen** [comment]
I mean there isn't any good reason we need these things to be multi-arch at all. Just so long as all arch get built along the way is good enough.

**Pull request merged**
